const employmentTypes = {
  FULL_TIME: "FULL_TIME",
  PART_TIME: "PART_TIME",
  CONTRACTOR: "CONTRACTOR",
  CONTRACT_TO_HIRE: "CONTRACT_TO_HIRE",
  TEMPORARY: "TEMPORARY",
  INTERN: "INTERN",
  VOLUNTEER: "VOLUNTEER",
  OTHER_EMPLOYMENT_TYPE: "OTHER_EMPLOYMENT_TYPE",
};

const compensationUnits = {};

const compensationTypes = {};

const compensationTypesToUnits = {
  HOURLY: 2080,
  DAILY: 260,
  WEEKLY: 52,
  MONTHLY: 12,
  ANNUAL: 1,
};

const jobBenefits = {
  JOB_BENEFIT_UNSPECIFIED: "JOB_BENEFIT_UNSPECIFIED",
  CHILD_CARE: "CHILD_CARE",
  DENTAL: "DENTAL",
  DOMESTIC_PARTNER: "DOMESTIC_PARTNE",
  FLEXIBLE_HOURS: "FLEXIBLE_HOURS",
  MEDICAL: "MEDICAL",
  LIFE_INSURANCE: "LIFE_INSURANCE",
  PARENTAL_LEAVE: "PARENTAL_LEAVE",
  RETIREMENT_PLAN: "RETIREMENT_PLAN",
  SICK_DAYS: "SICK_DAYS",
  VACATION: "VACATION",
  VISION: "VISION",
};

module.exports = {
  employmentTypes,
};
